nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmAuthToken: "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"

npmScopes:
  "@draug":
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "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"
